# solver/executor.py
# ------------------------------------------------------------
# Executes the plan generated by solver/llm_agent.py
# ------------------------------------------------------------
# Supports actions:
#   - download
#   - extract_pdf_table
#   - extract_html_table
#   - sum_column
#   - return_value
#   - submit_base64_plot
# ------------------------------------------------------------

import os
import base64
import pandas as pd
import pdfplumber
import matplotlib.pyplot as plt
import io
from typing import Dict, Any
from .fetch import download_resource


async def execute_plan(plan: Dict[str, Any], session: Dict[str, Any], working_dir: str) -> Dict[str, Any]:
    """
    Executes the steps returned by plan_with_llm().

    Returns {
        "answer": final_answer,
        "attachments": optional_list,
        "explain": text
    }
    """

    os.makedirs(working_dir, exist_ok=True)

    answer_obj = {
        "answer": None,
        "attachments": None,
        "explain": plan.get("explain")
    }

    last_table = None

    for step in plan.get("steps", []):
        action = step.get("action")

        # ------------------------------------------------------------
        # DOWNLOAD FILE
        # ------------------------------------------------------------
        if action == "download":
            url = step.get("url")
            local = await download_resource(url, working_dir)
            step["local_path"] = local

        # ------------------------------------------------------------
        # EXTRACT TABLE FROM PDF
        # ------------------------------------------------------------
        elif action == "extract_pdf_table":
            path = step.get("local_path") or step.get("path")
            page_no = step.get("page", 1)

            if not path:
                continue

            try:
                with pdfplumber.open(path) as pdf:
                    if 0 <= page_no - 1 < len(pdf.pages):
                        pg = pdf.pages[page_no - 1]
                        tables = pg.extract_tables()
                        if tables:
                            last_table = pd.DataFrame(tables[0][1:], columns=tables[0][0])
                        else:
                            last_table = None
                    else:
                        last_table = None
            except Exception:
                last_table = None

        # ------------------------------------------------------------
        # EXTRACT TABLE FROM HTML
        # ------------------------------------------------------------
        elif action == "extract_html_table":
            html = step.get("html")
            try:
                dfs = pd.read_html(html)
                index = step.get("index", 0)
                last_table = dfs[index]
            except Exception:
                last_table = None

        # ------------------------------------------------------------
        # SUM A COLUMN
        # ------------------------------------------------------------
        elif action == "sum_column":
            col = step.get("column")
            if last_table is not None and col in last_table.columns:
                series = pd.to_numeric(last_table[col], errors="coerce").fillna(0)
                total = series.sum()
                if abs(total - int(total)) < 1e-9:
                    total = int(total)
                answer_obj["answer"] = total
            else:
                answer_obj["answer"] = None

        # ------------------------------------------------------------
        # RETURN LITERAL VALUE
        # ------------------------------------------------------------
        elif action == "return_value":
            answer_obj["answer"] = step.get("value")

        # ------------------------------------------------------------
        # GENERATE BASE64 PNG PLOT
        # ------------------------------------------------------------
        elif action == "submit_base64_plot":
            if last_table is None or last_table.shape[1] < 2:
                continue
            x = last_table.iloc[:, 0]
            y = last_table.iloc[:, 1]

            plt.figure()
            plt.plot(x, y)
            buf = io.BytesIO()
            plt.savefig(buf, format="png")
            plt.close()
            buf.seek(0)
            b64 = base64.b64encode(buf.read()).decode("ascii")

            answer_obj["answer"] = f"data:image/png;base64,{b64}"
            answer_obj["attachments"] = [{"filename": "plot.png", "b64": b64}]

        # ------------------------------------------------------------
        # UNKNOWN ACTION (skip)
        # ------------------------------------------------------------
        else:
            continue

    # Use fallback final_value
    if answer_obj.get("answer") is None and plan.get("final_value") is not None:
        answer_obj["answer"] = plan.get("final_value")

    return answer_obj
